name: tests
on: 
  push:
  pull_request:
  schedule:
    - cron: "7 7 * * *"

jobs:

  test:
    name: run tests and lint 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: golangci-golint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.22.2
          ./bin/golangci-lint run -v ./...

      - name: gofmt check
        run: diff -u <(echo -n) <(gofmt -d ./)

      - name: go vet
        run: go vet -v ./...

      - name: go test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

